### ISSUE TITLE
Custom Methods Overwrite

### ISSUE THREAD

**Issue by onesocksid** [OmarElabd/RepositoryGenerator#4]
If I add a custom method to one of the repository interfaces...will the generator overwrite those changes if I run the tool again?

Also...one thing I found helpful in the past with generic repositories is a method to retrieve entities via query.  I modified the tt file slightly to include that method in the repo interface and the generic repo.  Just thought you might want to take a look at it to see if it's worth adding to your release.

This tool is great...saved me a ton of time...I've got over 100 entities I'm dealing with.

``` cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

public interface IRepository<T> where T : class
{
    IEnumerable<T> GetByQuery(Expression<Func<T, bool>> filter = null, Func<IQueryable<T>, IOrderedQueryable<T>> orderby = null);
    IEnumerable<T> GetAll();
    T GetById(int id);
    void Add(T entity);
    void Delete(T entity);
}
```

**Comment by OmarElabd** [comment]
Hi @onesocksid, I'm glad you find the tool useful! I'll definitely look into adding that method. If you run the generator again it will overwrite your code, so the the best thing i can recommend for that (I use this with all .tt files) is to make the generated code partial. And then add any extended code and methods inside those partial classes, so if you ever need to rerun the code generator again all the modifications you make will be in another partial class or interface and not be overwritten. Look into partial classes/interfaces if you are not familiar with them. Let me know if you have any questions.

**Comment by onesocksid** [comment]
Thanks Omar,

I’ll implement the partial classes to maintain those customizations.  Once again…great tool.  Saved me a ton of work.
